### ISSUE TITLE
Tone.js 404

### ISSUE THREAD

**Issue by cheesymoo** [posttool/posttool.github.io#1]
"http://cdn.tonejs.org/latest/Tone.min.js Failed to load resource: the server responded with a status of 404 (Not Found)"

**Comment by fenomas** [comment]
This is because the Tone.js CDN moved - new link is [here](https://tonejs.github.io/CDN/latest/Tone.min.js).

**Comment by posttool** [comment]
Fixed in 87205f92b686650f9b7c17331fab4a8d044a547f 
Thank you! Opening a new bug to update for the latest Tone...
